# Shell variables
# Generated by 'wal'
wallpaper='/home/fromsi/.config/nitrogen/fon.jpg'

# Special
background='#0e0f0f'
foreground='#dcc4a9'
cursor='#dcc4a9'

# Colors
color0='#0e0f0f'
color1='#6A5038'
color2='#695146'
color3='#8B663B'
color4='#986D54'
color5='#768143'
color6='#B28A64'
color7='#dcc4a9'
color8='#9a8976'
color9='#6A5038'
color10='#695146'
color11='#8B663B'
color12='#986D54'
color13='#768143'
color14='#B28A64'
color15='#dcc4a9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
