--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fromsi/.config/nitrogen/fon.jpg"

-- Special
background="#0e0f0f"
foreground="#dcc4a9"
cursor="#dcc4a9"

-- Colors
color0="#0e0f0f"
color1="#6A5038"
color2="#695146"
color3="#8B663B"
color4="#986D54"
color5="#768143"
color6="#B28A64"
color7="#dcc4a9"
color8="#9a8976"
color9="#6A5038"
color10="#695146"
color11="#8B663B"
color12="#986D54"
color13="#768143"
color14="#B28A64"
color15="#dcc4a9"
